# https://circleci.com/docs/2.0/configuration-reference/
version: 2
jobs:
  main:
    working_directory: ~/project
    docker:
      - image: quay.io/mkorejo/git_helm
    steps:
      - checkout
      - run:
          name: Package all the charts
          command: |
            for chart in $(find ~/project/src -type d -mindepth 1 -maxdepth 1)
              do helm package $chart -d releases/
            done
      - run:
          name: Re-index the repository
          command: helm repo index . --url https://mkorejo.github.io/helm_charts
      - add_ssh_keys
      - run:
          name: Commit and push
          command: |
            git config --global user.email "infra-apps-uploader@blackhole.net"
            git config --global user.name "infra-apps Uploader"
            git add index.yaml
            git add releases/*.tgz
            git commit -m "CircleCI Helm chart upload [skip ci]"
            git push

workflows:
  version: 2
  build_and_upload:
    jobs:
      - main:
          filters:
            branches:
              only: master