{{- if .Values.certManager.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Release.Name }}-cert-manager
  namespace: {{ .Values.general.namespace }}
{{- if .Values.certManager.finalizer.enabled }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
{{- end }}
spec:
  destination:
    namespace: {{ .Values.certManager.namespace }}
    server: {{ .Values.general.destination.server }}
  project: default
  source:
    chart: {{ .Values.certManager.source.chart }}
    repoURL: {{ .Values.certManager.source.repoURL }}
    targetRevision: {{ .Values.certManager.source.targetRevision }}
    helm:
      values: |
{{ toYaml .Values.certManager.spec | indent 8 }}
  syncPolicy:
    automated:
      prune: true
{{- end }}
---
{{- if .Values.certManager.enabled }}
{{- if .Values.certManager.clusterIssuer.enabled }}
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: {{ .Values.certManager.issuer.name }}
spec:
  acme:
    # Email address used for ACME registration and communication about issues/certificate expiration
    email: {{ .Values.certManager.issuer.email }}
    # The ACME server URL
    server: {{ .Values.certManager.issuer.server }}
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: {{ .Values.certManager.issuer.name }}-acme-issuer-account-key
    solvers:
  {{- if .Values.certManager.issuer.aws.iam_sa.enabled }}
    - dns01:
        route53:
          region: {{ .Values.certManager.issuer.aws.region }}
          hostedZoneID: {{ .Values.certManager.issuer.aws.hostedZoneID }}
          role: {{ .Values.certManager.issuer.aws.iam_sa.role }}
  {{- else }}
    - dns01:
        route53:
          accessKeyID: {{ .Values.certManager.issuer.aws.accessKeyID }}
          hostedZoneID: {{ .Values.certManager.issuer.aws.hostedZoneID }}
          region: {{ .Values.certManager.issuer.aws.region }}
          secretAccessKeySecretRef:
            name: {{ .Values.certManager.issuer.aws.secretAccessKeySecretRef.name }}
            key: {{ .Values.certManager.issuer.aws.secretAccessKeySecretRef.key }}
  {{- end }}
{{- end }}