{{- if .Values.certManager.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # Keep this static so the webhook endpoint will work
  name: cert-manager
  namespace: {{ .Values.general.namespace }}
{{- if .Values.certManager.finalizer.enabled }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
{{- end }}
spec:
  destination:
    namespace: {{ .Values.certManager.namespace }}
    server: {{ .Values.general.destination.server }}
  project: default
  source:
    chart: {{ .Values.certManager.source.chart }}
    repoURL: {{ .Values.certManager.source.repoURL }}
    targetRevision: {{ .Values.certManager.source.targetRevision }}
    helm:
      values: |
{{ toYaml .Values.certManager.spec | indent 8 }}
  syncPolicy:
    automated:
      prune: true
{{- end }}