{{- if .Values.externalDNS.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Release.Name }}-external-dns
  namespace: {{ .Values.general.namespace }}
{{- if .Values.externalDNS.finalizer.enabled }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
{{- end }}
spec:
  destination:
    namespace: {{ .Values.externalDNS.namespace }}
    server: {{ .Values.general.destination.server }}
  project: default
  source:
    chart: {{ .Values.externalDNS.source.chart }}
    repoURL: {{ .Values.externalDNS.source.repoURL }}
    targetRevision: {{ .Values.externalDNS.source.targetRevision }}
    helm:
      values: |
{{ toYaml .Values.externalDNS.spec | indent 8 }}
  syncPolicy:
    automated:
      prune: true
{{- end }}